name: Deploy to AWS

on:
  push:
    branches: [dev, main, deploy-with-open-next]

env:
  CDK_DEFAULT_ACCOUNT: ${{vars.CDK_DEFAULT_ACCOUNT}}
  CDK_DEFAULT_REGION: ${{vars.CDK_DEFAULT_REGION}}
  # WWW
  NEXT_PUBLIC_HUBSPOT_API: ${{vars.NEXT_PUBLIC_HUBSPOT_API}}
  STRAPI_API_URL: ${{vars.STRAPI_API_URL}}
  STRAPI_API_TOKEN: ${{secrets.STRAPI_API_TOKEN}}
  # CMS
  APP_KEYS: ${{secrets.APP_KEYS}}
  API_TOKEN_SALT: ${{secrets.API_TOKEN_SALT}}
  ADMIN_JWT_SECRET: ${{secrets.ADMIN_JWT_SECRET}}
  TRANSFER_TOKEN_SALT: ${{secrets.TRANSFER_TOKEN_SALT}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE: ${{vars.STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE}}

jobs:
  deploy-cms:
    name: Deploy CMS
    runs-on: 'ubuntu-latest'
    environment: ${{github.ref == 'refs/heads/main' && 'prod' || 'dev'}}
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get the branch name
        id: get_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        shell: bash

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment for ${{github.job.environment.name}}
        id: deployment
        with:
          token: '${{github.token}}'
          environment: ${{github.job.environment.name}}
          ref: ${{steps.get_branch.outputs.branch}}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      
      - name: Add .env file in cms
        run: |
          cd apps/cms
          touch .env
          echo APP_KEYS=$APP_KEYS >> .env
          echo API_TOKEN_SALT=$API_TOKEN_SALT >> .env
          echo ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET >> .env
          echo TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT >> .env
          echo STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE=$STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
          cat .env

      - name: Build cms
        run: npm run build
      
      - name: Zip cms
        run: zip -r strapi.zip ./* -x node_modules/\* apps/cms/node_modules\* apps/www/\* infrastructures/\*
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{vars.CDK_DEFAULT_ACCOUNT}}:role/github-role
          aws-region: ${{vars.CDK_DEFAULT_REGION}}

      - name: Deploying
        run: cd infrastructures/cms && npx cdk deploy StrapiStack --require-approval never

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{github.token}}'
          state: 'success'
          deployment-id: ${{steps.deployment.outputs.deployment_id}}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{github.token}}'
          state: 'failure'
          deployment-id: ${{steps.deployment.outputs.deployment_id}}
  # deploy-www:
  #   # needs: deploy-cms
  #   name: Deploy WWW
  #   runs-on: [self-hosted, 'codebuild']
  #   environment: ${{github.ref == 'refs/heads/main' && 'prod' || 'dev'}}
  #   permissions:
  #     id-token: write
  #     contents: read
  #     deployments: write
  #   steps:

  #     - name: Checkout the repository
  #       uses: actions/checkout@v4

  #     - name: Get the branch name
  #       id: get_branch
  #       run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
  #       shell: bash

  #     - uses: chrnorm/deployment-action@v2
  #       name: Create GitHub deployment for ${{github.job.environment.name}}
  #       id: deployment
  #       with:
  #         token: '${{github.token}}'
  #         environment: ${{github.job.environment.name}}
  #         ref: ${{steps.get_branch.outputs.branch}}

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.x'

  #     - uses: pnpm/action-setup@v2
  #       name: Install pnpm
  #       with:
  #         version: 8
  #         run_install: false

  #     - name: Install dependencies
  #       run: |
  #         pnpm install
      
  #     - name: Add .env file in www
  #       run: |
  #         cd apps/www
  #         touch .env
  #         echo NEXT_PUBLIC_HUBSPOT_API=$NEXT_PUBLIC_HUBSPOT_API >> .env
  #         echo STRAPI_API_URL=$STRAPI_API_URL >> .env
  #         echo STRAPI_API_TOKEN=$STRAPI_API_TOKEN >> .env
  #         cat .env

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         role-to-assume: arn:aws:iam::${{vars.CDK_DEFAULT_ACCOUNT}}:role/github-role
  #         aws-region: ${{vars.CDK_DEFAULT_REGION}}

  #     - name: Deploying
  #       run: |
  #         cd infrastructures/www && npx cdk deploy NextjsStack --require-approval never

  #     - name: Update deployment status (success)
  #       if: success()
  #       uses: chrnorm/deployment-status@v2
  #       with:
  #         token: '${{github.token}}'
  #         state: 'success'
  #         deployment-id: ${{steps.deployment.outputs.deployment_id}}

  #     - name: Update deployment status (failure)
  #       if: failure()
  #       uses: chrnorm/deployment-status@v2
  #       with:
  #         token: '${{github.token}}'
  #         state: 'failure'
  #         deployment-id: ${{steps.deployment.outputs.deployment_id}}
